### PR TITLE
Bump to llvm-12, rebasing out-of-tree patches onto it

### PR DESCRIPTION
**Pull request by pfez**
This PR is still a draft.

It's known to compile, and pass all the llvm testsuite with `orc install --test llvm`, with the only pre-requisite that `orchestra` is based on https://github.com/revng/orchestra/pull/36

`revng` can be successfully built from this, but there are still some failing tests (see https://github.com/revng/revng/pull/76).

This patchset is still dirty: there are still some explictly reverted out-of-tree patches in the history. They are not required for building `llvm`, nor for `revng`, but they might still be needed for successfully building some downstream project (like `revng-c`, `caliban`, or `cold-revng`). However, until all `revng` tests pass, we are not able to verify this on downstream projects. When we fix the `revng` tests failing, I'll figure out if these pending reverted patches need to be applied (so I'll remove the revert commit), or can be dropped (so I'll leave them entirely out of the new history).

@aleclearmind when you're done fixing `revng` tests, I'll figure out this pending reverts issues an update the PR.

### CODE REVIEW

**Comment by pfez** [comment]
**UPDATE**
- I managed to compile all our downstream projects up to `ui/cold-revng`
- I dropped the useless reverts, since it's confirmed they are not needed anymore
- There are still failing tests in `revng` and `revng-c`

**Comment by aleclearmind** [comment]
Looks great! LLVM 12, here we come.

Just a couple of comments:
1. "APFixedPointTest.cpp: fix C++20 compilation error": can you briefly describe the problem in the commit message? Dumping the error is not very nice.
2. "Fix C++20 UTF8 string literals" is a bit overkill IMO. It uses a series of macro tricks to fix a bug that doesn't really concern us in a test. I would have been fine with disabling the test. This kind of effort makes sense if we want to upstream the fixes, but updating LLVM is already quite time consuming as it is now.
3. "Add support to Dominators for FilteredGraphTraits": do we really, really, *really* need to rename `DomTreeNodeBase` to `DomTreeNodeOnView` and the like? Looking at the patchset with proper default values the patch could shrink in size significantly. A change in a well isolated feature ends up touching files everywhere. It feels like it increases the rebase burden with little return.

**Comment by aleclearmind** [comment]
We have a [failing test](https://rev.ng/gitlab/revng/orchestra/-/jobs/8140#L2983) due to the fact that we're running the test suite as root. Basically, a command is expected to fail but it doesn't since root bypasses permissions checks.
[Gentoo is experiencing the bug too](https://bugs.gentoo.org/775050).

Given also the other problematic tests, I suggest we have a series of commits in our LLVM fork that disable tests that we know are going to fail but we don't really care that much. Then, every time we upgrade LLVM we drop those commits and see if any of these issue has been solved.
It's quite a waste of time trying to fix this stuff for us and increases the friction towards upgrading LLVM, which is very important for us.

I know this is suboptimal, but I think it's the most reasonable thing to do.

These are the two tests that are failing due to permission issues:
```
  LLVM :: tools/llvm-ar/error-opening-permission.test
  LLVM :: tools/llvm-elfabi/fail-file-write.test
```
Can you please disable them?

**Comment by pfez** [comment]
> These are the two tests that are failing due to permission issues:
> 
> ```
>   LLVM :: tools/llvm-ar/error-opening-permission.test
>   LLVM :: tools/llvm-elfabi/fail-file-write.test
> ```
> 
> Can you please disable them?

Done!

**Comment by aleclearmind** [comment]
OK, the "APFixedPointTest.cpp: fix C++20 compilation error" thing is done, and the CI passes is OKGO.

**Comment by pfez** [comment]
> OK, once the "APFixedPointTest.cpp: fix C++20 compilation error" thing is done, and the CI passes is OKGO.

Done! See if you like the commit message better.

**Comment by aleclearmind** [comment]
> Done! See if you like the commit message better.

Looks great.
Now running on the CI.

**Comment by aleclearmind** [comment]
Merged in c97371c. Thanks!

**Pull request closed without merging**
